title: Posters
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'These samples of posters were designed by Thomas Ockerse from 1965 through 2020.'
updated_by: 241dc15f-5b2a-47ac-9111-7bcf1230f589
updated_at: 1641317994
blueprint: disciplines
