title: Print
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'These samples were designed for a variety of published books, magazines, brochures, and other printed matter. The projects started during the early part of Tom’s career and continued throughout.'
updated_by: 241dc15f-5b2a-47ac-9111-7bcf1230f589
updated_at: 1641317968
blueprint: disciplines
