title: Projects
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Projects in this segment reflect a complexity of parts, communication means and ideas.'
updated_by: 241dc15f-5b2a-47ac-9111-7bcf1230f589
updated_at: 1641318041
blueprint: disciplines
