<?php

require_once 'vendor/autoload.php';

use Aws\S3\S3Client;
use Aws\Exception\AwsException;

class RealS3ToSupabaseMigrator
{
    private $s3Client;
    private $bucket;
    private $supabaseUrl;
    private $supabaseKey;
    private $tempDir;
    private $batchSize = 50;
    private $processedCount = 0;
    private $errorCount = 0;
    private $startTime;
    private $progressFile = 'migration-progress.json';

    public function __construct()
    {
        $this->loadEnv();
        $this->tempDir = 'temp';
        $this->startTime = microtime(true);

        // Initialize S3 client with SSL verification disabled
        $this->s3Client = new S3Client([
            'version' => 'latest',
            'region' => $_ENV['AWS_DEFAULT_REGION'],
            'credentials' => [
                'key' => $_ENV['AWS_ACCESS_KEY_ID'],
                'secret' => $_ENV['AWS_SECRET_ACCESS_KEY'],
            ],
            'http' => [
                'verify' => false,
            ],
        ]);
        
        $this->bucket = $_ENV['AWS_BUCKET'];
        $this->supabaseUrl = $_ENV['SUPABASE_URL'] ?? '';
        $this->supabaseKey = $_ENV['SUPABASE_ANON_KEY'] ?? '';

        if (empty($this->supabaseUrl) || empty($this->supabaseKey)) {
            throw new Exception("Supabase URL or Anon Key is not configured in your .env file.");
        }
    }

    private function loadEnv()
    {
        $envFile = '.env';
        if (file_exists($envFile)) {
            $lines = file($envFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
            foreach ($lines as $line) {
                if (strpos($line, '=') !== false && strpos($line, '#') !== 0) {
                    list($key, $value) = explode('=', $line, 2);
                    $_ENV[trim($key)] = trim($value, '"');
                }
            }
        }
    }

    public function runFullMigration()
    {
        echo "=== REAL S3 TO SUPABASE MIGRATION ===\n";
        echo "This will insert data into your existing Supabase tables.\n";
        echo "Bucket: {$this->bucket}\n";
        echo "Start time: " . date('Y-m-d H:i:s') . "\n\n";

        // $this->createSupabaseTables(); // No longer needed, tables created manually.

        $totalObjects = $this->getTotalObjectCount();
        echo "Total objects to migrate: {$totalObjects}\n";
        echo "Batch size: {$this->batchSize}\n\n";

        $this->createProgressFile($totalObjects);

        $continuationToken = null;
        do {
            $result = $this->listS3ContentsBatch($continuationToken);
            $this->processBatch($result['objects']);
            $continuationToken = $result['continuationToken'];

            $this->saveProgress();
            $this->showProgress($totalObjects);
            usleep(100000); // 0.1 second delay

        } while ($continuationToken);

        $this->showFinalResults($totalObjects);
    }

    /*
    private function createSupabaseTables()
    {
        echo "Attempting to create Supabase tables if they don't exist...\n";

        $assetsTableSQL = "
        CREATE TABLE IF NOT EXISTS public.assets (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            filename TEXT,
            original_key TEXT UNIQUE,
            file_type TEXT,
            file_size BIGINT,
            file_url TEXT,
            metadata JSONB,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            updated_at TIMESTAMPTZ DEFAULT NOW()
        );
        CREATE INDEX IF NOT EXISTS idx_assets_file_type ON public.assets(file_type);
        CREATE INDEX IF NOT EXISTS idx_assets_metadata ON public.assets USING GIN(metadata);
        ";

        $collectionsTableSQL = "
        CREATE TABLE IF NOT EXISTS public.collections (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT UNIQUE,
            description TEXT,
            category TEXT,
            year INTEGER,
            asset_count INTEGER DEFAULT 0,
            created_at TIMESTAMPTZ DEFAULT NOW(),
            updated_at TIMESTAMPTZ DEFAULT NOW()
        );
        CREATE INDEX IF NOT EXISTS idx_collections_category ON public.collections(category);
        CREATE INDEX IF NOT EXISTS idx_collections_year ON public.collections(year);
        ";

        if ($this->executeSupabaseSQL($assetsTableSQL) && $this->executeSupabaseSQL($collectionsTableSQL)) {
            echo "Supabase tables check/creation complete.\n\n";
        } else {
            echo "Warning: There was an issue with table creation. It might be due to permissions or existing tables with conflicting definitions.\n\n";
        }
    }
    
    private function executeSupabaseSQL($sql)
    {
        $url = $this->supabaseUrl . '/rest/v1/rpc/exec';
    
        $ch = curl_init($url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, [
            'apikey: ' . $this->supabaseKey,
            'Authorization: Bearer ' . $this->supabaseKey,
            'Content-Type: application/json'
        ]);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode(['sql' => $sql]));
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); // For local dev if needed
    
        $response = curl_exec($ch);
        $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
        curl_close($ch);
    
        if ($httpCode >= 200 && $httpCode < 300) {
            return true;
        } else {
            echo "SQL execution failed with HTTP code: $httpCode\n";
            echo "Response: $response\n";
            return false;
        }
    }
    */


    private function getTotalObjectCount()
    {
        try {
            $iterator = $this->s3Client->getIterator('ListObjectsV2', [
                'Bucket' => $this->bucket
            ]);
            return count(iterator_to_array($iterator));
        } catch (AwsException $e) {
            echo "Error getting total count: " . $e->getMessage() . "\n";
            return 0;
        }
    }

    private function processBatch($objects)
    {
        foreach ($objects as $object) {
            try {
                $assetData = $this->prepareAssetData($object);
                if ($this->migrateAssetToSupabase($assetData)) {
                    $this->processedCount++;
                    echo "✓ {$assetData['filename']}\n";
                } else {
                    $this->errorCount++;
                    echo "✗ {$assetData['filename']}\n";
                }
            } catch (Exception $e) {
                $this->errorCount++;
                echo "✗ Error with {$object['key']}: " . $e->getMessage() . "\n";
            }
        }
    }

    private function listS3ContentsBatch($continuationToken = null)
    {
        try {
            $params = [
                'Bucket' => $this->bucket,
                'MaxKeys' => $this->batchSize,
            ];
            if ($continuationToken) {
                $params['ContinuationToken'] = $continuationToken;
            }
            
            $result = $this->s3Client->listObjectsV2($params);
            
            $objects = [];
            if (!empty($result['Contents'])) {
                foreach ($result['Contents'] as $object) {
                    $objects[] = [
                        'key' => $object['Key'],
                        'size' => $object['Size'],
                        'lastModified' => $object['LastModified'],
                        'url' => $this->s3Client->getObjectUrl($this->bucket, $object['Key'])
                    ];
                }
            }

            return [
                'objects' => $objects,
                'continuationToken' => $result['NextContinuationToken'] ?? null
            ];

        } catch (AwsException $e) {
            echo "Error listing S3 contents: " . $e->getMessage() . "\n";
            return ['objects' => [], 'continuationToken' => null];
        }
    }

    private function prepareAssetData($object)
    {
        $extension = strtolower(pathinfo($object['key'], PATHINFO_EXTENSION));
        $filename = basename($object['key']);
        
        $fileType = $this->categorizeFileType($extension);
        $metadata = $this->extractMetadata($object['key']);
        
        return [
            'filename' => $filename,
            'original_key' => $object['key'],
            'file_type' => $fileType,
            'file_size' => $object['size'],
            'file_url' => $object['url'],
            'metadata' => json_encode(array_merge($metadata, [
                'extension' => $extension,
                'last_modified' => $object['lastModified']->format('Y-m-d H:i:s'),
                'size_mb' => round($object['size'] / 1024 / 1024, 2)
            ]))
        ];
    }

    private function categorizeFileType($extension)
    {
        $videoExtensions = ['mp4', 'm4v', 'mov', 'avi', 'mkv'];
        $imageExtensions = ['jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg'];
        $documentExtensions = ['pdf', 'doc', 'docx', 'txt', 'md', 'yaml'];
        
        if (in_array($extension, $videoExtensions)) return 'video';
        if (in_array($extension, $imageExtensions)) return 'image';
        if (in_array($extension, $documentExtensions)) return 'document';
        return 'other';
    }

    private function extractMetadata($key)
    {
        $metadata = [];
        if (preg_match('/^(\d{2})/', basename($key), $matches)) {
            $metadata['year'] = '20' . $matches[1];
        }
        $categories = [
            'grthc' => 'graphic_theory', 'hist' => 'history', 'opres' => 'op_research',
            'relad' => 'related_design', 'semf' => 'semiotics_foundation', 'senstu' => 'senior_studio',
            'textperim' => 'text_perimeter', 'uemeaning' => 'ue_meaning', 'vissys' => 'visual_systems'
        ];
        foreach ($categories as $str => $cat) {
            if (strpos($key, $str) !== false) {
                $metadata['category'] = $cat;
                break;
            }
        }
        if (preg_match('/(\d+\.?\d*)s/', $key, $matches)) {
            $metadata['duration_seconds'] = floatval($matches[1]);
        }
        if (preg_match('/(\d+)p/', $key, $matches)) {
            $metadata['resolution'] = $matches[1] . 'p';
        }
        return $metadata;
    }

    private function migrateAssetToSupabase($assetData)
    {
        try {
            $url = $this->supabaseUrl . '/rest/v1/assets';

            $ch = curl_init();
            curl_setopt($ch, CURLOPT_URL, $url);
            curl_setopt($ch, CURLOPT_POST, true);
            curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($assetData));
            curl_setopt($ch, CURLOPT_HTTPHEADER, [
                'Content-Type: application/json',
                'Authorization: Bearer ' . $this->supabaseKey,
                'apikey: ' . $this->supabaseKey,
                'Prefer: resolution=merge-duplicates' // important to avoid errors on reruns
            ]);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false); // For local dev if needed
            curl_setopt($ch, CURLOPT_TIMEOUT, 30);

            $response = curl_exec($ch);
            $httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
            $error = curl_error($ch);
            curl_close($ch);

            if ($error) {
                echo "cURL Error: {$error}\n";
                return false;
            }
            
            if ($httpCode >= 200 && $httpCode < 300) {
                return true;
            } else {
                echo " (HTTP {$httpCode})\n";
                if ($response) { echo "  Response: {$response}\n"; }
                return false;
            }
        } catch (Exception $e) {
            echo " (Exception: {$e->getMessage()})\n";
            return false;
        }
    }
    
    private function createProgressFile($totalObjects)
    {
        $progressData = [
            'total_objects' => $totalObjects,
            'processed_count' => 0,
            'error_count' => 0,
            'start_time' => date('Y-m-d H:i:s'),
            'last_updated' => date('Y-m-d H:i:s')
        ];
        file_put_contents($this->progressFile, json_encode($progressData, JSON_PRETTY_PRINT));
    }

    private function saveProgress()
    {
        $progressData = json_decode(file_get_contents($this->progressFile), true);
        $progressData['processed_count'] = $this->processedCount;
        $progressData['error_count'] = $this->errorCount;
        $progressData['last_updated'] = date('Y-m-d H:i:s');
        file_put_contents($this->progressFile, json_encode($progressData, JSON_PRETTY_PRINT));
    }
    
    private function showProgress($totalObjects)
    {
        if ($totalObjects == 0) return;
        $processed = $this->processedCount + $this->errorCount;
        $percentage = round(($processed / $totalObjects) * 100, 2);
        $elapsed = round(microtime(true) - $this->startTime, 2);
        
        echo "\n--- Progress Update ---\n";
        echo "Processed: {$this->processedCount} | Errors: {$this->errorCount} | Total: {$totalObjects}\n";
        echo "Percentage: {$percentage}% | Elapsed: {$elapsed}s\n";
        
        if ($this->processedCount > 0) {
            $rate = round($this->processedCount / $elapsed, 2);
            $eta = $rate > 0 ? round(($totalObjects - $processed) / $rate, 2) : 'N/A';
            echo "Rate: {$rate} files/sec | ETA: {$eta}s\n";
        }
        echo "------------------------\n\n";
    }

    private function showFinalResults($totalObjects)
    {
        $totalTime = round(microtime(true) - $this->startTime, 2);
        $successRate = $totalObjects > 0 ? round(($this->processedCount / $totalObjects) * 100, 2) : 0;
        
        echo "\n" . str_repeat("=", 40) . "\n";
        echo "=== MIGRATION COMPLETE ===\n";
        echo "Total time: {$totalTime} seconds\n";
        echo "Successfully migrated: {$this->processedCount} assets\n";
        echo "Errors: {$this->errorCount} assets\n";
        echo "Total processed: " . ($this->processedCount + $this->errorCount) . " assets\n";
        echo "Success rate: {$successRate}%\n";
        echo "End time: " . date('Y-m-d H:i:s') . "\n";
        echo str_repeat("=", 40) . "\n";
        
        $this->generateSummaryReport();
    }

    private function generateSummaryReport()
    {
        $totalObjects = $this->getTotalObjectCount();
        $report = [
            'migration_summary' => [
                'total_objects' => $totalObjects,
                'processed_count' => $this->processedCount,
                'error_count' => $this->errorCount,
                'success_rate' => $totalObjects > 0 ? round(($this->processedCount / $totalObjects) * 100, 2) : 0,
                'start_time' => date('Y-m-d H:i:s', $this->startTime),
                'end_time' => date('Y-m-d H:i:s'),
                'total_duration_seconds' => round(microtime(true) - $this->startTime, 2)
            ],
            'next_steps' => [
                "Review the 'assets' and 'collections' tables in your Supabase project.",
                "Begin frontend development using the 'react-frontend-setup.md' guide.",
                "Connect the React app to Supabase to fetch and display the migrated data."
            ]
        ];
        
        file_put_contents('migration-summary-real.json', json_encode($report, JSON_PRETTY_PRINT));
        echo "\nReal migration summary saved to: migration-summary-real.json\n";
    }

    public function runDryRun($limit = 20)
    {
        echo "=== DRY RUN - REAL SCRIPT ===\n";
        echo "This will test S3 access and data preparation logic.\n";
        echo "It will NOT write anything to Supabase.\n";
        echo "Processing first {$limit} files...\n\n";
        
        $result = $this->listS3ContentsBatch(null);
        $objects = array_slice($result['objects'], 0, $limit);

        foreach ($objects as $object) {
            $assetData = $this->prepareAssetData($object);
            echo "Would migrate: {$assetData['filename']}\n";
            echo "  Key: {$assetData['original_key']}\n";
            echo "  Type: {$assetData['file_type']}\n";
            echo "  Data: " . json_encode($assetData) . "\n\n";
        }
        
        echo "Dry run completed. Checked " . count($objects) . " files.\n";
    }
}

// Command line argument parsing and execution logic
$options = getopt('', ['dry-run', 'limit:', 'help', 'full-migration']);

if (isset($options['help'])) {
    echo "Usage: php migrate-to-supabase-real.php [options]\n\n";
    echo "Options:\n";
    echo "  --full-migration   Run the full, real migration to Supabase. DANGEROUS.\n";
    echo "  --dry-run          Test S3 access and data prep. Safe to run. (DEFAULT)\n";
    echo "  --limit=N          Limit dry run to N files (default: 20).\n";
    echo "  --help             Show this help message.\n\n";
    echo "To run the actual migration, you MUST use the --full-migration flag.\n";
    exit(0);
}

try {
    $migrator = new RealS3ToSupabaseMigrator();

    if (isset($options['full-migration'])) {
        $migrator->runFullMigration();
    } else {
        $limit = isset($options['limit']) ? (int)$options['limit'] : 20;
        $migrator->runDryRun($limit);
    }
} catch (Exception $e) {
    echo "\n\nCRITICAL ERROR: " . $e->getMessage() . "\n";
    echo "Please check your .env file and Supabase project settings.\n";
    exit(1);
}
