title: ABSTRACT
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: "Experiments with\_"
      -
        type: text
        marks:
          -
            type: bold
          -
            type: italic
        text: Concretism
      -
        type: text
        text: "\_using abstract forms, constructions, and systems for visual poetry."
updated_by: 241dc15f-5b2a-47ac-9111-7bcf1230f589
updated_at: 1641320774
blueprint: explorations
