title: BOOKED
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: "Experiments with\_"
      -
        type: text
        marks:
          -
            type: bold
          -
            type: italic
        text: Concretism
      -
        type: text
        text: "\_with the time/space medium of the book as a system for experience, often called bookworks, from which content and meaning are derived from all its parts, actions, and experiences. For this to happen the whole book as a medium system must be considered in terms of principles of\_"
      -
        type: text
        marks:
          -
            type: italic
        text: 'Concrete Poetry'
      -
        type: text
        text: "\_wherein an\_“atomization” of meaning takes place from parts and wholes and their synthesis but is now supplemented by the user’s time-space experience.\_\_In that union of experience, the book object becomes truly a poetic object, which holistic experience naturally draws out a depth of awareness that is sourced both from the external relationship yet also an implicit sense of awareness of being one with the Spirit and all that it is experiencing. This union represents the essential values brought out by seeing relationships to the ever growing dynamic for interconnections based on the doctrine of shells that is ever unfolding and enfolding."
updated_by: 241dc15f-5b2a-47ac-9111-7bcf1230f589
updated_at: 1641320846
blueprint: explorations
