title: EVENTS
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: "As an introduction to experiments in\_"
      -
        type: text
        marks:
          -
            type: bold
          -
            type: italic
        text: Concretism
      -
        type: text
        text: "\_using walks, experiences, and celebrations as sources and means from which fragments were documentraced to create a poetic object. The final poetic objects were all formulated on the principles of documentracings relative to their approach conceptually and then procedurally: as\_extracted ("
      -
        type: text
        marks:
          -
            type: italic
        text: documentraced
      -
        type: text
        text: ') fragments or parts from larger wholes, the approach of “right action” to determine what was to be extracted (according to some systemic principle), and the objective extractions themselves (versus our usual subjective tendency to achieve projected results).'
updated_by: 241dc15f-5b2a-47ac-9111-7bcf1230f589
updated_at: 1641320864
blueprint: explorations
