title: FOUND
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: "These experiments in\_"
      -
        type: text
        marks:
          -
            type: bold
          -
            type: italic
        text: Concretism
      -
        type: text
        text: "\_use found objects as concrete poems in which constellations of words and images create concrete poetry: postage stamps found on envelopes and their accidental fusion with postal cancellations. These works\_present the viewer with a different kind of “stamp collection”— one that focuses attention on the relationship of existing postage stamps found with their cancellations on mailed envelopes. Although their relationships may appear obvious to serve their practical purpose and thus not require any further attention, this creates an unexpected expressive result with often a powerful poetic result—which we tend to overlook due to their small scale (and indeed, we often overlook the small things in life!)."
updated_by: 241dc15f-5b2a-47ac-9111-7bcf1230f589
updated_at: 1641320793
blueprint: explorations
