title: VERBIVISUAL
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: "Poetic experiments in\_"
      -
        type: text
        marks:
          -
            type: bold
          -
            type: italic
        text: Concretism
      -
        type: text
        marks:
          -
            type: bold
        text: "\_"
      -
        type: text
        text: "present a search of meaning using written, visual, and other means to spark an infinity of ideas. This so-called\_"
      -
        type: text
        marks:
          -
            type: italic
        text: verbivovisual
      -
        type: text
        text: "\_poetry has three sub-groups: 2-dimensional, 3-dimensional, and drawings."
updated_by: 241dc15f-5b2a-47ac-9111-7bcf1230f589
updated_at: 1641320753
blueprint: explorations
