title: CONCRETISM
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'The theory of CONCRETISM encourages the study of objects as dynamic systems for a depth of meaning and relational values revealing an inner world, considered “abstract” because invisible, that unfolds a network of relationships and values as a world of ONENESS, opposite to the ordinary sense of “reality” in the world of appearances.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'In other words, this theory of inquiry overturns the generalized notion that the world around us is “real” and “concrete,” and designates the inner, intangible world as “abstract” by realizing that the hidden networking begins to reflect relationships of underlying principals directing values and meaning far beyond the limited factor of appearances and into a unity of wholeness or: Oneness. That unity of Oneness reveals the true “Concrete” world with a capital “C” for a true sense of Reality with a capital “R”!'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Examples of this are discovering sacred geometry as the underlying principle for good form, learning the inner “character” of a person and a true sense of identity with that individual, and gaining a sense of awe and wonder when brought into a relationship with a huge tree. In this sense, we perceive relationships as these, extracted from that deep sense of wholeness, from that REALITY, from that CONCRETE Reality, to derive a sense of true Poetic Essence, a knowing that is powerful, dynamic, and a truly living sense of CONCRETISM.'
  -
    type: paragraph
    content:
      -
        type: text
        text: "Theo van Doesburg coined the term Concretism in 1930 while leading the Dutch\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "De Stijl\_"
      -
        type: text
        text: "group of artists and designers (e.g., Piet Mondrian, Gerrit Rietveld, and others) who sought to capture and express the “spiritual” in art. Their search led them to use visual abstractions thus avoiding mere repetition of the external world of objects. Also influencing the group was the deep interest from studies happening locally called\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "theosophy\_"
      -
        type: text
        text: "that presented a scientific view to render life more intelligible by connecting us with wholeness. After studying\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "theosophy\_"
      -
        type: text
        text: 'Theo van Doesburg concluded that their search, intended to express the spiritual in art, was a search to find that true sense of Reality at the heart of meaning and value. In other words, using the “abstract” means searching for truth with the creation of artifacts from which we gain a sense of wholeness. Theo decided that this creation is not limited to abstract shapes and colors but can also be found in other ways to serve the same purpose of inquiry in the search of Reality, hence a true sense of Reality from that principle of Oneness—which he called Concretism.'
  -
    type: paragraph
    content:
      -
        type: text
        text: "For an inquiry into this sense of wholeness Frank Lloyd Wright, for example, believed that\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "“nature’s secrets could only be discovered by diligent contemplation.”\_"
      -
        type: text
        text: "He said that\_"
      -
        type: text
        marks:
          -
            type: italic
        text: '“Reality and truth were not to be found on the surface of things but require extensive probing and thought to yield valuable lessons.”'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Therefore, we must learn to practice Right Action, action that comes with critical discernment, inseeing, contemplation, and mindfulness to bring about an inner, poetic, spiritual sense of mediation which stimulates within the designer the full nature of creative capacities. Only from that can the process truly become a purposeful act of DESIGN with a capital D.'
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: "Theosophy\_"
      -
        type: text
        text: 'presents a vision of wholeness that inspires a fellowship united in study, meditation, and service. It encourages open-minded inquiry into the wisdom of the ages, respects the unity of all life, and helps people explore spiritual self-transformation. Theosophy holds an ethic on the fact that every action, feeling, and thought affect all other beings, which makes each of us capable of and responsible for contributing to the benefit of the whole.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Theosophy presents a body of knowledge that provides theory, practice, and techniques to enable us to free ourselves from the limitations of ordinary life. This knowledge is the Ancient Wisdom, the perennial philosophy, the wisdom tradition. Being universally true, it is found all over the world in many different forms, depending upon the time and circumstances and the people it is addressing. Theosophy is one version of this Ancient Wisdom in recent times. Derived from Greek roots meaning “divine wisdom,” it reveals a body of knowledge that tells us about our place in the universe and why the world is the way it is. Although it agrees in many respects with scientific theories, it goes beyond them in addressing unseen realities that we all experience, but often do not understand.'
updated_by: 241dc15f-5b2a-47ac-9111-7bcf1230f589
updated_at: 1641325638
blueprint: themes
