title: 'CONTEMPLATIVE DESIGN'
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'The theory of '
      -
        type: text
        marks:
          -
            type: bold
        text: 'contemplative design'
      -
        type: text
        text: " studies\_how to stimulate one’s depth of consciousness."
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: 'Design as contemplative practice'
      -
        type: text
        text: "\_means to practice design via the gateway to consciousness. In short, contemplation involves paying attention, and attention nurtures the capacity for insight into the actions taken. This is only accomplished by means of the simultaneous act of the introspective and extrospective, an awareness of oneself and the activity involved. This means a practice of attention to give thought its right place."
  -
    type: paragraph
    content:
      -
        type: text
        text: "While science has long rejected introspection when studying consciousness, it has begun to acknowledge that cognitive control and attention are essential to understanding—and understanding means first to understand oneself. Behavioral science and psychology confirm that\_who we are"
      -
        type: text
        marks:
          -
            type: bold
        text: "\_"
      -
        type: text
        text: "filters our perceptions that color our understanding and our projections. Knowing oneself means to become aware of that filter and its projections. Without this self-knowledge we can only perpetuate the past and limit ourselves from seeing anything new. In that sense we can say that\_the practice of contemplation is essential for digesting life."
updated_by: 241dc15f-5b2a-47ac-9111-7bcf1230f589
updated_at: 1641325815
blueprint: themes
