title: LANGUAGE
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: "The theory of LANGUAGE\_studies the systemic ordering of relationships to serve communication."
  -
    type: paragraph
    content:
      -
        type: text
        text: "We use\_"
      -
        type: text
        marks:
          -
            type: bold
        text: language
      -
        type: text
        text: "\_to form relationships among parts and wholes according to a set of rules. While this is also the principle for all “systems,” to use the term “language” changes our point of view to identify how the relational dynamics form meaningful relationships. The linguistic view of language offers three so-called “"
      -
        type: text
        marks:
          -
            type: italic
        text: dimensions
      -
        type: text
        text: '” for analysis, and three ways to “'
      -
        type: text
        marks:
          -
            type: italic
        text: use
      -
        type: text
        text: "” language to communicate.\_"
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: "The three\_"
      -
        type: text
        marks:
          -
            type: bold
          -
            type: italic
        text: dimensions
      -
        type: text
        marks:
          -
            type: bold
        text: "\_of language"
      -
        type: text
        text: "\_are the syntactic, semantic, and pragmatic. Syntactics\_represents the formal and structural relations of parts and wholes.\_Semantics\_represents what parts and whole mean to convey ideas.\_Pragmatics\_represents the functional relation of parts and wholes that serve the purpose of communication. These three dimensions have a concentric relationship, with the syntactic being inside, the pragmatic outside, and the semantic in between the two. However, their relations are interdependent, and therefore inseparable except for their analysis and study.\_\_"
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: "The\_"
      -
        type: text
        marks:
          -
            type: bold
          -
            type: italic
        text: use
      -
        type: text
        marks:
          -
            type: bold
        text: "\_of language to communicate"
      -
        type: text
        text: "\_means to generalize from three points of view (which I) named: the\_"
      -
        type: text
        marks:
          -
            type: bold
        text: practical
      -
        type: text
        text: ",\_"
      -
        type: text
        marks:
          -
            type: bold
        text: dialectical
      -
        type: text
        text: ", and\_"
      -
        type: text
        marks:
          -
            type: bold
        text: poetical
      -
        type: text
        text: ". The\_"
      -
        type: text
        marks:
          -
            type: bold
        text: practical
      -
        type: text
        text: "\_serves to communicate with a singleness of meaning, characteristic of informational clarity and directness. The"
      -
        type: text
        marks:
          -
            type: bold
        text: dialectical
      -
        type: text
        text: "\_use of language serves to communicate rhetorically, meaning to encourage, council, or persuade, having some ulterior motive typical of advertising, propaganda, and political speeches. The\_"
      -
        type: text
        marks:
          -
            type: bold
        text: poetical
      -
        type: text
        text: "\_use of language intends to inspire and deepen consciousness to expand and broaden understanding.\_These three uses relate in a concentric relationship, starting in the center with the immediate need to represent, and then expands to color information subjectively, or then to objectively stimulate expanded perceptions. As a concentric dynamic this also means the basic need to communicate is present in all three.\_"
updated_by: 241dc15f-5b2a-47ac-9111-7bcf1230f589
updated_at: 1641325673
blueprint: themes
