title: 'Concrete Books'
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: "The course\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "Concrete Books\_"
      -
        type: text
        text: 'explores the potential of the book object as a dynamic form to incite feelings, ideas, and inspirations. In that potential the book as an object is viewed especially as an interactive time/space medium for a total (or hyper) experience wherein the “reader” (or user, or experiencer of the object) is both co-pilot and co-author unfolding a narrative of ideas from what is seen, touched, heard, performed, or read.'
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: italic
        text: "Concrete Books\_"
      -
        type: text
        text: "explores\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "experience\_"
      -
        type: text
        text: "and\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "poetics\_"
      -
        type: text
        text: "as the core issues in the design process. Since\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "experience\_"
      -
        type: text
        text: "is the basis for all knowing while\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "poetics\_"
      -
        type: text
        text: "reflects the breadth and depth of knowledge, attention to these aspects help one tap into the depth of perception and innovation. Our means for inquiry is to constantly produce bookworks via experimentation and play, supplemented by an array of relational topics (semiotics, mindfulness, perennial philosophy, indeterminacy and the spiritual in art). To optimize studio experience for production some class time includes alternate means for work, play, insight and inspiration.\_"
  -
    type: paragraph
    content:
      -
        type: text
        text: "The purpose and objectives are: to stimulate insight in the student’s design process and creativity; to explore\_"
      -
        type: text
        marks:
          -
            type: italic
        text: 'design as a contemplative practice'
      -
        type: text
        text: '; and to inquire into wholeness and the poetics of design.'
updated_by: a726f1e0-85b0-48e3-939b-db6b8482c1d0
updated_at: 1670089214
blueprint: courses
thumbnail_slides:
  - 22cbks.001.jpeg
  - 22cbks.002.jpeg
  - 22cbks.003.jpeg
  - 22cbks.004.jpeg
  - 22cbks.005.jpeg
  - 22cbks.006.jpeg
  - 22cbks.007.jpeg
