title: 'Graduate Studio 1: Unfolding Meaning'
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: "Graduate Studio 1\_builds on practical skills and experiences graduate students are expected to have by going deeper into the underlying design principles and abstract theories according to personal choice."
updated_by: 241dc15f-5b2a-47ac-9111-7bcf1230f589
updated_at: 1641320271
blueprint: courses
