title: 'Relational Design'
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: "This course,\_"
      -
        type: text
        marks:
          -
            type: italic
        text: 'Relational Design'
      -
        type: text
        text: ", explores the complexity of relational factors for visual communication objects to function in the vast range of human experiences and a changing social environment.\_"
  -
    type: paragraph
    content:
      -
        type: text
        text: "The premise is that designed objects function in this pattern of relationships that in turn shape identity, information, and behavior.\_This course also responds to the growing world paradigm of collaboration and integrative thinking that value the experience of group dynamics to considers how new media can serve social and information needs, explores ways to solve problems, and stimulates imagination and innovation."
  -
    type: paragraph
    content:
      -
        type: text
        text: "Course projects are very hands-on to explore these interrelationships among form, function, meaning, and audience. The course also emphasizes making (incl. presentations!) and critical visual thinking, with methods and concepts offered as theoretical (vs. prescriptive) tools. The course promotes\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "innovation\_"
      -
        type: text
        text: "and\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "entrepreneurship\_"
      -
        type: text
        text: "in the design of products for human experiences; encourages\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "strategic thinking\_"
      -
        type: text
        text: "to manage complexity; practices\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "convergent\_"
      -
        type: text
        text: "and\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "divergent thinking\_"
      -
        type: text
        text: "critical to the design process; practices\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "collaboration\_"
      -
        type: text
        text: "by sharing individual vision and skills in a group context; inspires\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "authenticity\_"
      -
        type: text
        text: "for new insights in the design process; and stimulates\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "self-reliance\_"
      -
        type: text
        text: 'in navigating uncertainty and change.'
updated_by: 241dc15f-5b2a-47ac-9111-7bcf1230f589
updated_at: 1641320335
blueprint: courses
