title: 'Senior Studio'
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'The course'
      -
        type: text
        marks:
          -
            type: italic
        text: "\_Senior Studio 1"
      -
        type: text
        text: "\_provides a platform for students to develop their “voice” and personal interests for the practice of graphic design. The core assignments address opportunities and complexities in graphic design and relates these to personal interests. The studio realizes its pedagogical goals by engaging in real world issues or “"
      -
        type: text
        marks:
          -
            type: italic
        text: information
      -
        type: text
        text: '” driven projects. This approach requires analysis of informational content, the context in which this will function, and explores options for re-telling the content in visually meaningful and engaging ways.'
updated_by: 241dc15f-5b2a-47ac-9111-7bcf1230f589
updated_at: 1641320226
blueprint: courses
