title: 'TexTperience TexTperiment'
description:
  -
    type: paragraph
    content:
      -
        type: text
        marks:
          -
            type: bold
        text: TexTperience/TexTperiment
      -
        type: text
        text: "\_is a course for open search and experimentation. It encourages experiments with the way we experience the\_"
      -
        type: text
        marks:
          -
            type: italic
        text: 'visible word,'
      -
        type: text
        text: "\_and how visual form can serve its depth and breadth for meaning."
  -
    type: paragraph
    content:
      -
        type: text
        text: "We consider how\_"
      -
        type: text
        marks:
          -
            type: bold
        text: "the visible form\_"
      -
        type: text
        text: "of the word can serve its purpose to\_"
      -
        type: text
        marks:
          -
            type: bold
        text: read
      -
        type: text
        text: ",\_"
      -
        type: text
        marks:
          -
            type: bold
        text: frame
      -
        type: text
        text: ",\_"
      -
        type: text
        marks:
          -
            type: bold
        text: "engage\_"
      -
        type: text
        text: "and\_"
      -
        type: text
        marks:
          -
            type: bold
        text: "inspire\_"
      -
        type: text
        text: "the depth and breadth of meaning. After some brief introductory work to establish common ground, the course format becomes an open laboratory for\_"
      -
        type: text
        marks:
          -
            type: bold
        text: "individual\_"
      -
        type: text
        text: "(OR collaborative)\_"
      -
        type: text
        marks:
          -
            type: bold
        text: 'interests and inquiries'
      -
        type: text
        text: ", such as to explore: the de/re/con/struction of words; letters/words in 3-d space, in motion, on the screen, projected, performed; words and the sensory experience of materiality, sound, projection; text in public environments, virtual spaces (posters? branding? sculpture? visual poetry? etc.); and whatever one’s interest is and can envision.\_"
  -
    type: paragraph
    content:
      -
        type: text
        text: 'As a studio course making and visual thinking are emphasized. Topics for inquiry can range from the practical to the poetical to the pure experimental. Course work can supplement other course interests (such as thesis work and degree projects). Not forgetting that letters serve the purpose to make words visible, we consider how the visual form can serve that purpose to help frame, engage, narrate and inspire the depth and breadth of meaning. The focus is on in-depth inquiry and experimentation to liberate & empower our interests.'
updated_by: a726f1e0-85b0-48e3-939b-db6b8482c1d0
updated_at: 1670098755
blueprint: courses
thumbnail_slides:
  - 22textperim01.jpeg
  - 22textperim02.jpeg
  - 22textperim03.jpeg
  - 22textperim05.jpeg
  - 22textperim06.jpeg
  - 22textperim07.jpeg
