title: 'Visual Systems'
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'The course '
      -
        type: text
        marks:
          -
            type: italic
        text: 'Visual Systems'
      -
        type: text
        text: "\_investigates the nature and dynamics of wholeness: the tension between parts and wholes; how systems connect, relate and influence parts in relationship; and how these principles can serve the purpose of designed products."
  -
    type: paragraph
    content:
      -
        type: text
        text: "Human beings are, intrinsically organizers and pattern seekers, apparently due to a drive within us toward wholeness and integration for a sense of order, harmony, and unity in everything we are compelled to perceive this universe of complexity (including our personal relationship to it) as an operating “system” having underlying rules for principles that serve structure, meaning and function.\_\_"
  -
    type: paragraph
    content:
      -
        type: text
        text: "Hence, system thinking plays a significant role in every part of our lives, whether we do so consciously or instinctively, and so becomes a natural inherent feature in design, in every part of design without exception.\_\_"
  -
    type: paragraph
    content:
      -
        type: text
        text: "This course\_"
      -
        type: text
        marks:
          -
            type: italic
        text: 'Visual Systems'
      -
        type: text
        text: "\_is an inquiry into systems thinking. This inquiry reflects two aspects of design: a)\_"
      -
        type: text
        marks:
          -
            type: italic
        text: 'system as a way of looking at objects in their holistic sense'
      -
        type: text
        text: "\_as product of interacting parts and principles (from contrast, hierarchy, pattern, grid, proportion, symmetry, to narrative, information, networking, etc.); and b) as a\_"
      -
        type: text
        marks:
          -
            type: italic
        text: "generating system to create objects—i.e., a process for search to invent and innovate\_"
      -
        type: text
        text: "in an apparent universe of synchronous order and chance.\_"
  -
    type: paragraph
    content:
      -
        type: text
        text: "Although systems theory opens a vast territory of potentially related design interests (e.g., social, cultural, environmental, etc.) we focus on the dynamics of the visual language to open perceptual awareness and deepen insight into the nature of design, with our main question being:\_"
      -
        type: text
        marks:
          -
            type: italic
        text: 'how can we reveal the subtle in the obvious, the limitless in the limited?'
updated_by: a726f1e0-85b0-48e3-939b-db6b8482c1d0
updated_at: 1670099058
blueprint: courses
thumbnail_slides:
  - 22vissys01.jpeg
  - 22vissys02.jpeg
  - 22vissys04.jpeg
  - 22vissys05.jpeg
  - 22vissys06.jpeg
  - 22vissys07.jpeg
